# Generated by Django 5.0.4 on 2024-04-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_suddenexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='person',
            new_name='personRef',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='type',
            new_name='typeRef',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='person',
            new_name='personRef',
        ),
        migrations.RenameField(
            model_name='suddenexpense',
            old_name='person',
            new_name='personRef',
        ),
    ]
